version: '3.7'
x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
services:
  postgres:
    image: postgis/postgis:12-3.0
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - '6379'
    volumes:
      - redis:/data
    command: redis-server --appendonly yes

  app:
    <<: *app
    command: /bin/sh -c "yarn --check-files && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - '3000:3000'
    environment:
      TZ: 'Asia/Tokyo'
      HA4DB_DEVELOPMENT_DATABASE_URL: postgis://postgres:password@postgres/ha4db_development
      HA4DB_TEST_DATABASE_URL: postgis://postgres:password@postgres/ha4db_test
      WEBPACKER_DEV_SERVER_HOST: frontend
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    depends_on:
      - postgres
      - redis
    stdin_open: true
    tty: true

  frontend:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      <<: *env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

volumes:
  bundle:
  node_modules:
  packs:
  pgdata:
  redis:
