# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

# rubocop:disable Metrics/BlockLength
RSpec.describe '/bridge_content_injuries', type: :request do
  before do
    @user = FactoryBot.create(:user)
    allow_any_instance_of(ActionDispatch::Request).to receive(:session).and_return({ user_id: @user.id })
    @bridge = FactoryBot.create(:bridge)
    @regular_inspection = FactoryBot.create(:regular_inspection, bridge: @bridge)
    @component = FactoryBot.create(:component, bridge: @bridge)
    @injury = FactoryBot.create(:injury, regular_inspection: @regular_inspection, component: @component)
    @bridge_content = FactoryBot.create(:bridge_content, regular_inspection: @regular_inspection)
  end

  # BridgeContentInjury. As you add validations to BridgeContentInjury, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.build(:bridge_content_injury, injury: @injury, bridge_content: @bridge_content).attributes
  end

  let(:invalid_attributes) do
    bridge_content_injury = FactoryBot.build(:bridge_content_injury, injury: @injury, bridge_content: @bridge_content)
    bridge_content_injury.bridge_content = nil
    bridge_content_injury.attributes
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BridgeContentInjury.create! valid_attributes
      get regular_inspection_injury_bridge_content_injuries_url(@regular_inspection, @injury)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bridge_content_injury = BridgeContentInjury.create! valid_attributes
      get regular_inspection_injury_bridge_content_injury_url(@regular_inspection, @injury, bridge_content_injury)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_regular_inspection_injury_bridge_content_injury_url(@regular_inspection, @injury)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      bridge_content_injury = BridgeContentInjury.create! valid_attributes
      get edit_regular_inspection_injury_bridge_content_injury_url(@regular_inspection, @injury, bridge_content_injury)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BridgeContentInjury' do
        expect do
          post regular_inspection_injury_bridge_content_injuries_url(@regular_inspection, @injury),
               params: { bridge_content_injury: valid_attributes }
        end.to change(BridgeContentInjury, :count).by(1)
      end

      it 'redirects to the created bridge_content_injury' do
        post regular_inspection_injury_bridge_content_injuries_url(@regular_inspection, @injury),
             params: { bridge_content_injury: valid_attributes }
        expect(response).to redirect_to(
          regular_inspection_injury_bridge_content_injury_url(@regular_inspection,
                                                              @injury,
                                                              BridgeContentInjury.last)
        )
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BridgeContentInjury' do
        expect do
          post regular_inspection_injury_bridge_content_injuries_url(@regular_inspection, @injury),
               params: { bridge_content_injury: invalid_attributes }
        end.to change(BridgeContentInjury, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post regular_inspection_injury_bridge_content_injuries_url(@regular_inspection, @injury),
             params: { bridge_content_injury: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        @new_bridge_content = FactoryBot.create(:bridge_content, regular_inspection: @regular_inspection)
        bridge_content_injury = FactoryBot.build(:bridge_content_injury, bridge_content: @new_bridge_content).attributes
        bridge_content_injury['seek'] = 2
        bridge_content_injury
      end

      it 'updates the requested bridge_content_injury' do
        bridge_content_injury = BridgeContentInjury.create! valid_attributes
        patch regular_inspection_injury_bridge_content_injury_url(@regular_inspection,
                                                                  @injury,
                                                                  bridge_content_injury),
              params: { bridge_content_injury: new_attributes }
        bridge_content_injury.reload
        expect(bridge_content_injury.bridge_content).to eq(@new_bridge_content)
        expect(bridge_content_injury.seek).to eq(2)
      end

      it 'redirects to the bridge_content_injury' do
        bridge_content_injury = BridgeContentInjury.create! valid_attributes
        patch regular_inspection_injury_bridge_content_injury_url(@regular_inspection,
                                                                  @injury,
                                                                  bridge_content_injury),
              params: { bridge_content_injury: new_attributes }
        bridge_content_injury.reload
        expect(response).to redirect_to(
          regular_inspection_injury_bridge_content_injury_url(@regular_inspection, @injury, bridge_content_injury)
        )
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bridge_content_injury = BridgeContentInjury.create! valid_attributes
        patch regular_inspection_injury_bridge_content_injury_url(@regular_inspection,
                                                                  @injury,
                                                                  bridge_content_injury),
              params: { bridge_content_injury: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bridge_content_injury' do
      bridge_content_injury = BridgeContentInjury.create! valid_attributes
      expect do
        delete regular_inspection_injury_bridge_content_injury_url(@regular_inspection,
                                                                   @injury,
                                                                   bridge_content_injury)
      end.to change(BridgeContentInjury, :count).by(-1)
    end

    it 'redirects to the bridge_content_injuries list' do
      bridge_content_injury = BridgeContentInjury.create! valid_attributes
      delete regular_inspection_injury_bridge_content_injury_url(@regular_inspection,
                                                                 @injury,
                                                                 bridge_content_injury)
      expect(response).to redirect_to(
        regular_inspection_injury_bridge_content_injuries_url(@regular_inspection, @injury)
      )
    end
  end
end
# rubocop:enable Metrics/BlockLength
