# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

# rubocop:disable Metrics/BlockLength
RSpec.describe '/components', type: :request do
  before do
    @user = FactoryBot.create(:user)
    allow_any_instance_of(ActionDispatch::Request).to receive(:session).and_return({ user_id: @user.id })
    @bridge = FactoryBot.create(:bridge)
  end

  # Component. As you add validations to Component, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.build(:component, bridge: @bridge).attributes
  end

  let(:invalid_attributes) do
    component = FactoryBot.build(:component, bridge: @bridge)
    component.component_category = nil
    component.attributes
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Component.create! valid_attributes
      get bridge_components_url(@bridge)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      component = Component.create! valid_attributes
      get bridge_component_url(@bridge, component)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bridge_component_url(@bridge)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      component = Component.create! valid_attributes
      get edit_bridge_component_url(@bridge, component)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Component' do
        expect do
          post bridge_components_url(@bridge), params: { component: valid_attributes }
        end.to change(Component, :count).by(1)
      end

      it 'redirects to the created component' do
        post bridge_components_url(@bridge), params: { component: valid_attributes }
        expect(response).to redirect_to(bridge_component_url(@bridge, Component.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Component' do
        expect do
          post bridge_components_url(@bridge), params: { component: invalid_attributes }
        end.to change(Component, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bridge_components_url(@bridge), params: { component: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        component = FactoryBot.build(:component, bridge: @bridge)
        component.component_category = Component.categories[:other]
        component.attributes
      end

      it 'updates the requested component' do
        component = Component.create! valid_attributes
        patch bridge_component_url(@bridge, component), params: { component: new_attributes }
        component.reload
        expect(component.component_category).to eq(6)
      end

      it 'redirects to the component' do
        component = Component.create! valid_attributes
        patch bridge_component_url(@bridge, component), params: { component: new_attributes }
        component.reload
        expect(response).to redirect_to(bridge_component_url(@bridge, component))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        component = Component.create! valid_attributes
        patch bridge_component_url(@bridge, component), params: { component: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested component' do
      component = Component.create! valid_attributes
      expect do
        delete bridge_component_url(@bridge, component)
      end.to change(Component, :count).by(-1)
    end

    it 'redirects to the components list' do
      component = Component.create! valid_attributes
      delete bridge_component_url(@bridge, component)
      expect(response).to redirect_to(bridge_components_url(@bridge))
    end
  end
end
# rubocop:enable Metrics/BlockLength
