# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

# rubocop:disable Metrics/BlockLength
RSpec.describe '/diagnoses', type: :request do
  before do
    @user = FactoryBot.create(:user)
    allow_any_instance_of(ActionDispatch::Request).to receive(:session).and_return({ user_id: @user.id })
    @bridge = FactoryBot.create(:bridge)
    @regular_inspection = FactoryBot.create(:regular_inspection, bridge: @bridge)
    @component = FactoryBot.create(:component, bridge: @bridge)
    @injury = FactoryBot.create(:injury, regular_inspection: @regular_inspection, component: @component)
  end

  # Diagnosis. As you add validations to Diagnosis, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.build(:diagnosis, regular_inspection: @regular_inspection, injury: @injury).attributes
  end

  let(:invalid_attributes) do
    regular_inspection = FactoryBot.build(:diagnosis, regular_inspection: @regular_inspection, injury: @injury)
    regular_inspection.injury = nil
    regular_inspection.result = Diagnosis.diagnosis_results[:two]
    regular_inspection.attributes
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Diagnosis.create! valid_attributes
      get regular_inspection_diagnoses_url(@regular_inspection)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      diagnosis = Diagnosis.create! valid_attributes
      get regular_inspection_diagnosis_url(@regular_inspection, diagnosis)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_regular_inspection_diagnosis_url(@regular_inspection)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      diagnosis = Diagnosis.create! valid_attributes
      get edit_regular_inspection_diagnosis_url(@regular_inspection, diagnosis)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Diagnosis' do
        expect do
          post regular_inspection_diagnoses_url(@regular_inspection), params: { diagnosis: valid_attributes }
        end.to change(Diagnosis, :count).by(1)
      end

      it 'redirects to the created diagnosis' do
        post regular_inspection_diagnoses_url(@regular_inspection), params: { diagnosis: valid_attributes }
        expect(response).to redirect_to(regular_inspection_diagnosis_url(@regular_inspection, Diagnosis.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Diagnosis' do
        expect do
          post regular_inspection_diagnoses_url(@regular_inspection), params: { diagnosis: invalid_attributes }
        end.to change(Diagnosis, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post regular_inspection_diagnoses_url(@regular_inspection), params: { diagnosis: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        regular_inspection = FactoryBot.build(:diagnosis, regular_inspection: @regular_inspection, injury: @injury)
        regular_inspection.result = Diagnosis.diagnosis_results[:three]
        regular_inspection.attributes
      end

      it 'updates the requested diagnosis' do
        diagnosis = Diagnosis.create! valid_attributes
        patch regular_inspection_diagnosis_url(@regular_inspection, diagnosis), params: { diagnosis: new_attributes }
        diagnosis.reload
        expect(diagnosis.result).to eq(Diagnosis.diagnosis_results[:three])
      end

      it 'redirects to the diagnosis' do
        diagnosis = Diagnosis.create! valid_attributes
        patch regular_inspection_diagnosis_url(@regular_inspection, diagnosis), params: { diagnosis: new_attributes }
        diagnosis.reload
        expect(response).to redirect_to(regular_inspection_diagnosis_url(@regular_inspection, diagnosis))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        diagnosis = Diagnosis.create! valid_attributes
        patch regular_inspection_diagnosis_url(@regular_inspection, diagnosis),
              params: { diagnosis: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested diagnosis' do
      diagnosis = Diagnosis.create! valid_attributes
      expect do
        delete regular_inspection_diagnosis_url(@regular_inspection, diagnosis)
      end.to change(Diagnosis, :count).by(-1)
    end

    it 'redirects to the diagnoses list' do
      diagnosis = Diagnosis.create! valid_attributes
      delete regular_inspection_diagnosis_url(@regular_inspection, diagnosis)
      expect(response).to redirect_to(regular_inspection_diagnoses_url(@regular_inspection))
    end
  end
end
# rubocop:enable Metrics/BlockLength
