# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

# rubocop:disable Metrics/BlockLength
RSpec.describe '/injuries', type: :request do
  before do
    @user = FactoryBot.create(:user)
    allow_any_instance_of(ActionDispatch::Request).to receive(:session).and_return({ user_id: @user.id })
    @bridge = FactoryBot.create(:bridge)
    @regular_inspection = FactoryBot.create(:regular_inspection, bridge: @bridge)
    @component = FactoryBot.create(:component, bridge: @bridge)
  end

  # Injury. As you add validations to Injury, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.build(:injury, regular_inspection: @regular_inspection, component: @component).attributes
  end

  let(:invalid_attributes) do
    invalid_value = FactoryBot.build(:injury, regular_inspection: @regular_inspection, component: @component)
    invalid_value.component = nil
    invalid_value.attributes
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Injury.create! valid_attributes
      get regular_inspection_injuries_url(@regular_inspection)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      injury = Injury.create! valid_attributes
      get regular_inspection_injury_url(@regular_inspection, injury)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_regular_inspection_injury_url(@regular_inspection)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      injury = Injury.create! valid_attributes
      get edit_regular_inspection_injury_url(@regular_inspection, injury)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Injury' do
        expect do
          post regular_inspection_injuries_url(@regular_inspection), params: { injury: valid_attributes }
        end.to change(Injury, :count).by(1)
      end

      it 'redirects to the created injury' do
        post regular_inspection_injuries_url(@regular_inspection), params: { injury: valid_attributes }
        expect(response).to redirect_to(regular_inspection_injury_url(@regular_inspection, Injury.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Injury' do
        expect do
          post regular_inspection_injuries_url(@regular_inspection), params: { injury: invalid_attributes }
        end.to change(Injury, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post regular_inspection_injuries_url(@regular_inspection), params: { injury: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        new_value = FactoryBot.build(:injury, regular_inspection: @regular_inspection, component: @component).attributes
        new_value['injury_type'] = 'test!'
        new_value['unit'] = 'm'
        new_value
      end

      it 'updates the requested injury' do
        injury = Injury.create! valid_attributes
        patch regular_inspection_injury_url(@regular_inspection, injury), params: { injury: new_attributes }
        injury.reload
        expect(injury.injury_type).to eq('test!')
        expect(injury.unit).to eq('m')
      end

      it 'redirects to the injury' do
        injury = Injury.create! valid_attributes
        patch regular_inspection_injury_url(@regular_inspection, injury), params: { injury: new_attributes }
        injury.reload
        expect(response).to redirect_to(regular_inspection_injury_url(@regular_inspection, injury))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        injury = Injury.create! valid_attributes
        patch regular_inspection_injury_url(@regular_inspection, injury), params: { injury: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested injury' do
      injury = Injury.create! valid_attributes
      expect do
        delete regular_inspection_injury_url(@regular_inspection, injury)
      end.to change(Injury, :count).by(-1)
    end

    it 'redirects to the injuries list' do
      injury = Injury.create! valid_attributes
      delete regular_inspection_injury_url(@regular_inspection, injury)
      expect(response).to redirect_to(regular_inspection_injury_url(@regular_inspection))
    end
  end
end
# rubocop:enable Metrics/BlockLength
