# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

# rubocop:disable Metrics/BlockLength
RSpec.describe '/inspections', type: :request do
  before do
    @user = FactoryBot.create(:user)
    allow_any_instance_of(ActionDispatch::Request).to receive(:session).and_return({ user_id: @user.id })
    @bridge = FactoryBot.create(:bridge)
  end
  # Inspection. As you add validations to Inspection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.build(:inspection, bridge: @bridge).attributes
  end

  let(:invalid_attributes) do
    attributes = FactoryBot.build(:inspection, bridge: @bridge).attributes
    attributes['title'] = ''
    attributes
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Inspection.create! valid_attributes
      get bridge_inspections_url(@bridge)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      inspection = Inspection.create! valid_attributes
      get bridge_inspections_url(@bridge, inspection)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bridge_inspection_url(@bridge)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      inspection = Inspection.create! valid_attributes
      get edit_bridge_inspection_url(@bridge, inspection)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Inspection' do
        expect do
          post bridge_inspections_url(@bridge), params: { inspection: valid_attributes }
        end.to change(Inspection, :count).by(1)
      end

      it 'redirects to the created inspection' do
        post bridge_inspections_url(@bridge), params: { inspection: valid_attributes }
        expect(response).to redirect_to(bridge_inspection_url(@bridge, Inspection.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Inspection' do
        expect do
          post bridge_inspections_url(@bridge), params: { inspection: invalid_attributes }
        end.to change(Inspection, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bridge_inspections_url(@bridge), params: { inspection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        attributes = valid_attributes
        attributes['category'] = :superstructure_slab
        attributes
      end

      it 'updates the requested inspection' do
        inspection = Inspection.create! valid_attributes
        patch bridge_inspection_url(@bridge, inspection), params: { inspection: new_attributes }
        inspection.reload
        expect(inspection.category).to eq('superstructure_slab')
      end

      it 'redirects to the inspection' do
        inspection = Inspection.create! valid_attributes
        patch bridge_inspection_url(@bridge, inspection), params: { inspection: new_attributes }
        inspection.reload
        expect(response).to redirect_to(bridge_inspection_url(@bridge, inspection))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        inspection = Inspection.create! valid_attributes
        patch bridge_inspection_url(@bridge, inspection), params: { inspection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested inspection' do
      inspection = Inspection.create! valid_attributes
      expect do
        delete bridge_inspection_url(@bridge, inspection)
      end.to change(Inspection, :count).by(-1)
    end

    it 'redirects to the inspections list' do
      inspection = Inspection.create! valid_attributes
      delete bridge_inspection_url(@bridge, inspection)
      expect(response).to redirect_to(bridge_inspections_url(@bridge))
    end
  end
end
# rubocop:enable Metrics/BlockLength
