# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

# rubocop:disable Metrics/BlockLength
RSpec.describe '/soundnesses', type: :request do
  before do
    @user = FactoryBot.create(:user)
    allow_any_instance_of(ActionDispatch::Request).to receive(:session).and_return({ user_id: @user.id })
    @bridge = FactoryBot.create(:bridge)
  end
  # Soundness. As you add validations to Soundness, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.build(:soundness, bridge: @bridge).attributes
  end

  let(:invalid_attributes) do
    attributes = FactoryBot.build(:soundness, bridge: @bridge).attributes
    attributes['evaluation'] = ''
    attributes
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Soundness.create! valid_attributes
      get bridge_soundnesses_url(@bridge)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      soundness = Soundness.create! valid_attributes
      get bridge_soundness_url(@bridge, soundness)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bridge_soundness_url(@bridge)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      soundness = Soundness.create! valid_attributes
      get edit_bridge_soundness_url(@bridge, soundness)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Soundness' do
        expect do
          post bridge_soundnesses_url(@bridge), params: { soundness: valid_attributes }
        end.to change(Soundness, :count).by(1)
      end

      it 'redirects to the created soundness' do
        post bridge_soundnesses_url(@bridge), params: { soundness: valid_attributes }
        expect(response).to redirect_to(bridge_soundness_url(@bridge, Soundness.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Soundness' do
        expect do
          post bridge_soundnesses_url(@bridge), params: { soundness: invalid_attributes }
        end.to change(Soundness, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bridge_soundnesses_url(@bridge), params: { soundness: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        attributes = valid_attributes
        attributes['evaluation'] = 'new text'
        attributes
      end

      it 'updates the requested soundness' do
        soundness = Soundness.create! valid_attributes
        patch bridge_soundness_url(@bridge, soundness), params: { soundness: new_attributes }
        soundness.reload
        expect(soundness.evaluation).to eq('new text')
      end

      it 'redirects to the soundness' do
        soundness = Soundness.create! valid_attributes
        patch bridge_soundness_url(@bridge, soundness), params: { soundness: new_attributes }
        soundness.reload
        expect(response).to redirect_to(bridge_soundness_url(@bridge, soundness))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        soundness = Soundness.create! valid_attributes
        patch bridge_soundness_url(@bridge, soundness), params: { soundness: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested soundness' do
      soundness = Soundness.create! valid_attributes
      expect do
        delete bridge_soundness_url(@bridge, soundness)
      end.to change(Soundness, :count).by(-1)
    end

    it 'redirects to the soundnesses list' do
      soundness = Soundness.create! valid_attributes
      delete bridge_soundness_url(@bridge, soundness)
      expect(response).to redirect_to(bridge_soundnesses_url(@bridge))
    end
  end
end
# rubocop:enable Metrics/BlockLength
